Update Passwall_x86_64.yml

diff --git a/.github/workflows/Passwall_x86_64.yml b/.github/workflows/Passwall_x86_64.yml
--- a/.github/workflows/Passwall_x86_64.yml
+++ b/.github/workflows/Passwall_x86_64.yml
@@ -33,12 +33,10 @@ jobs:
             # - arch: x86_64
             #   sdk_url: https://downloads.openwrt.org/releases/23.05.2/targets/x86/64/openwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
             - arch: x86_64
-              sdk_url: https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+              sdk_url: https://downloads.openwrt.org/releases/24.10.5/targets/x86/64/openwrt-sdk-24.10.5-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
+              sdk_ver: "24.10"
             # - arch: aarch64_cortex-a53
             #   sdk_url: https://downloads.openwrt.org/releases/23.05.2/targets/x86/64/openwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
-
-# - https://downloads.openwrt.org/releases/21.02.7/targets/x86/64/openwrt-sdk-21.02.7-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
-# - https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
 
     steps:
 
@@ -93,7 +91,7 @@ jobs:
           sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
           sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
           sudo -E apt-get -qq update
-          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
+          sudo -E apt-get -qq install build-essential zstd clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
@@ -107,33 +105,73 @@ jobs:
       #       mkdir -p $sdk/package
 
 
+          # wget -O openwrt-sdk.tar.xz ${{ matrix.sdk_url }}
+          # xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
+          # mv -f openwrt-sdk-* openwrt-sdk
+          # ls openwrt-sdk
 
       - name: Install OpenWrt SDK
         run: |
-          wget -O openwrt-sdk.tar.xz ${{ matrix.sdk_url }}
-          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
-          mv -f openwrt-sdk-* openwrt-sdk
-          ls openwrt-sdk
+
+          wget ${{ matrix.sdk_url }}
+          file_name=$(echo ${{matrix.sdk_url}} | awk -F/ '{print $NF}')
+          mkdir sdk && tar --zstd -x -f $file_name -C ./openwrt-sdk --strip-components=1
+          ls openwrt-sdk  
           echo 'CONFIG_ALL=y' >> openwrt-sdk/.config
 
 
-      - name: Build Package passwall
+      - name: Build Package passwall （old）
         run: |
-
           cd openwrt-sdk
-          echo "src-git pspackages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
-          echo 'CONFIG_ALL=y' >> .config
-          echo "src-git passwall https://github.com/Openwrt-Passwall/openwrt-passwall.git;main" >> "feeds.conf.default"
-          # echo "src-git passwall2 https://github.com/Openwrt-Passwall/openwrt-passwall2.git;main" >> "feeds.conf.default"
+          cat > feeds.conf.default << EOF
+          src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main
+          src-git base https://github.com/openwrt/openwrt.git;openwrt-${{ matrix.sdk_ver }}
+          src-git packages https://github.com/openwrt/packages.git;openwrt-${{ matrix.sdk_ver }}
+          src-git luci https://github.com/openwrt/luci.git;openwrt-${{ matrix.sdk_ver }}
+          src-git routing https://github.com/openwrt/routing.git;openwrt-${{ matrix.sdk_ver }}
+          src-git telephony https://github.com/openwrt/telephony.git;openwrt-${{ matrix.sdk_ver }}
+          EOF
+  
           ./scripts/feeds update -a
           ./scripts/feeds install -a
-
+  
+          #--------------------------------------begin_patches------------------------------------------
+          echo "Start applying the patch"
+  
+  
+          rm -rf temp_resp
+          git clone -b master --single-branch https://github.com/openwrt/packages.git temp_resp
+          echo "update golang version"
           rm -rf feeds/packages/lang/golang
-          git clone --depth 1 https://github.com/sbwml/packages_lang_golang -b 23.x feeds/packages/lang/golang
+          cp -r temp_resp/lang/golang feeds/packages/lang
+          echo "update rust version"
+          rm -rf feeds/packages/lang/rust
+          cp -r temp_resp/lang/rust feeds/packages/lang
+          rm -rf temp_resp
+  
+          git clone -b main --single-branch https://github.com/openwrt/openwrt.git temp_resp
+          cp -f temp_resp/scripts/patch-kernel.sh scripts/
+          rm -rf temp_resp
+  
+          echo "fixed rust host build error"
+          sed -i 's/--set=llvm\.download-ci-llvm=false/--set=llvm.download-ci-llvm=true/' feeds/packages/lang/rust/Makefile
+          grep -q -- '--ci false \\' feeds/packages/lang/rust/Makefile || sed -i '/x\.py \\/a \        --ci false \\' feeds/packages/lang/rust/Makefile
+  
+          ./scripts/feeds update -a
+          ./scripts/feeds install -a
+  
+          echo "Patch application completed"
+          #--------------------------------------end_patches--------------------------------------------
+  
+          # echo "CONFIG_ALL_NONSHARED=n" > .config
+          # echo "CONFIG_ALL_KMODS=n" >> .config
+          # echo "CONFIG_ALL=n" >> .config
+          # echo "CONFIG_AUTOREMOVE=n" >> .config
+          # echo "CONFIG_SIGNED_PACKAGES=n" >> .config
+          # make defconfig
 
           make defconfig
           make package/feeds/luci/luci-base/compile -j$(nproc)
-
           make package/feeds/passwall/luci-app-passwall/compile -j$(nproc)
           # make package/feeds/passwall2/luci-app-passwall2/compile -j$(nproc)
           find . -name "*.ipk" -print
@@ -145,6 +183,36 @@ jobs:
               echo $pkg
               make V=s package/feeds/pspackages/$pkg/compile -j$(nproc) || make package/feeds/pspackages/$pkg/compile -j1 V=sc || exit 0
           done
+
+        
+      # - name: Build Package passwall （old）
+      #   run: |
+
+      #     cd openwrt-sdk
+      #     echo "src-git pspackages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
+      #     echo 'CONFIG_ALL=y' >> .config
+      #     echo "src-git passwall https://github.com/Openwrt-Passwall/openwrt-passwall.git;main" >> "feeds.conf.default"
+      #     # echo "src-git passwall2 https://github.com/Openwrt-Passwall/openwrt-passwall2.git;main" >> "feeds.conf.default"
+      #     ./scripts/feeds update -a
+      #     ./scripts/feeds install -a
+
+      #     rm -rf feeds/packages/lang/golang
+      #     git clone --depth 1 https://github.com/sbwml/packages_lang_golang -b 23.x feeds/packages/lang/golang
+
+      #     make defconfig
+      #     make package/feeds/luci/luci-base/compile -j$(nproc)
+
+      #     make package/feeds/passwall/luci-app-passwall/compile -j$(nproc)
+      #     # make package/feeds/passwall2/luci-app-passwall2/compile -j$(nproc)
+      #     find . -name "*.ipk" -print
+      #     # make package/feeds/passwall/luci-app-passwall/compile -j$(nproc) || make package/feeds/passwall/luci-app-passwall/compile -j1 V=sc || exit 0
+      #     # make package/feeds/passwall2/luci-app-passwall2/compile -j$(nproc) || make package/feeds/passwall2/luci-app-passwall2/compile -j1 V=sc || exit 0
+      #     pkgs=$(ls package/feeds/pspackages)
+      #     for pkg in $pkgs
+      #     do
+      #         echo $pkg
+      #         make V=s package/feeds/pspackages/$pkg/compile -j$(nproc) || make package/feeds/pspackages/$pkg/compile -j1 V=sc || exit 0
+      #     done
           
 
       - name: Build Package adguardhome
@@ -156,9 +224,7 @@ jobs:
           git clone --depth 1 https://github.com/AoThen/luci-app-adguardhome.git package/luci-app-adguardhome
           make defconfig
           make package/feeds/luci/luci-base/compile V=s
-
           make package/luci-app-adguardhome/compile -j$(nproc) || make make package/luci-app-adguardhome/compile -j1 V=sc || exit 0
-
 
 
 
